### PR TITLE
Delete browserSandbox if false

### PR DESCRIPTION
**Pull request by RobbieTheWagner**
There was no way to disable this if you were on Electron 5.x, this should allow users to set it to `false` to remove it.

@malept thoughts on something like this?

### CODE REVIEW

**Comment by rwwagner90** [comment]
@malept I have been told repeatedly by the Snapcraft guys now that sandbox is only allowed for vetted developers, which are only big publishers like Google Chrome, Brave, etc. It seems to be next to impossible to apply to be a vetted developer or be allowed to use sandbox. With this in mind, perhaps we should remove the option entirely?

**Comment by mahnunchik** [comment]
@malept It seems it is better to  to use `allow-sandbox: false` according to the documentation: https://snapcraft.io/docs/browser-support-interface

**Comment by rwwagner90** [comment]
@mahnunchik this PR makes it configurable.

**Comment by davidwinter** [comment]
Can this PR please be reviewed and merged if working? Currently snap builds are currently not possible with electron-forge, making it impossible to use as a tool.

**Comment by davidwinter** [comment]
@rwwagner90 any chance you could add tests to cover the change so that the codecov bot passes? Also, if you could merge in the latest changes, then perhaps we could get @malept to merge the PR in?

**Comment by rwwagner90** [comment]
I clicked the update button to get it up to date with master. I could try to add a test, but I am not 100% sure this is the right solution, it just illustrates what I *think* should be done. I would love input and direction from @malept here!

**Comment by rwwagner90** [comment]
@malept are we interested in making this repo work again or not? If not, I'll close the PR.

**Comment by rwwagner90** [comment]
It seems like there are no intentions of updating this package to actually work with snap, so if anyone else lands here looking for a fix for broken electron-forge setup, please use https://github.com/davidwinter/electron-forge-maker-snap

**Comment by Igloczek** [comment]
Anyone know how to handle this topic now? 
- `electron-forge-maker-snap` is abandoned
- `@electron-forge/maker-snap` do basically nothing, just wraps this package and pass arch, src and dest to it
- this package is not handling the sandbox thingies properly on its own, since snap store automatically reject the builds
- adding `--no-sandbox` makes no difference

are there any docs, guides or something else that describes how this stuff should be used?

from what i see, big bois like vs-code are not even trying to use any of these tools and just create a snapcraft.conf file on on their own and call snapcraft CLI directly

is that the only way, since everything else simply doesn't work or maybe it's working but only "if you know you know" mode?

**Comment by RobbieTheWagner** [comment]
I am attempting to get `@electron-forge/maker-snap` working and it still seems to not work. Has anyone successfully gotten things to work?

**Comment by mahnunchik** [comment]
No, and it's been broken for a long time, but no one cares

**Pull request closed without merging**
